import type { AdminOrderSummary, PublicInvitation } from "@/lib/admin/types";

export const demoOrders: AdminOrderSummary[] = [
  {
    id: 1048,
    public_slug: "rina-fajar",
    customer_name: "Rina Paramita",
    customer_whatsapp: "+6281211101048",
    groom_name: "Fajar",
    bride_name: "Rina",
    package_slug: "premium",
    template_slug: "luxury-maroon",
    payment_status: "lunas",
    work_status: "data_lengkap",
    total_price: 148000,
    active_until: "2027-05-14T00:00:00+00:00",
    created_at: "2026-05-14T08:12:00+00:00",
  },
  {
    id: 1047,
    public_slug: "ayu-rizki",
    customer_name: "Ayu Maharani",
    customer_whatsapp: "+6285155347714",
    groom_name: "Rizki",
    bride_name: "Ayu",
    package_slug: "exclusive",
    template_slug: "garden-sage",
    payment_status: "menunggu",
    work_status: "dikerjakan",
    total_price: 373000,
    active_until: "2028-05-14T00:00:00+00:00",
    created_at: "2026-05-13T12:25:00+00:00",
  },
  {
    id: 1046,
    public_slug: "dewi-arman",
    customer_name: "Dewi Lestari",
    customer_whatsapp: "+6287788221046",
    groom_name: "Arman",
    bride_name: "Dewi",
    package_slug: "basic",
    template_slug: "classic-rose",
    payment_status: "lunas",
    work_status: "review",
    total_price: 74000,
    active_until: "2026-11-14T00:00:00+00:00",
    created_at: "2026-05-13T09:40:00+00:00",
  },
];

export const demoInvitation: PublicInvitation = {
  id: 1048,
  public_slug: "rina-fajar",
  customer_name: "Rina Paramita",
  groom_name: "Fajar",
  bride_name: "Rina",
  package_slug: "premium",
  template_slug: "luxury-maroon",
  payment_status: "lunas",
  work_status: "selesai",
  total_price: 148000,
  active_until: "2027-05-14T00:00:00+00:00",
  music_title: "Perfect - Ed Sheeran",
  love_story:
    "Berawal dari pertemuan sederhana, kami belajar bahwa rumah adalah seseorang yang membuat hari terasa tenang. Dengan penuh syukur, kami mengundang keluarga dan sahabat untuk menjadi bagian dari hari bahagia kami.",
  gift_account: "BCA 1234567890 a.n. Rina Paramita",
  notes: "Mohon doa restu dan kehadirannya.",
  order_events: [
    {
      event_type: "akad",
      title: "Akad Nikah",
      event_date: "2026-08-22",
      event_time: "09:00",
      location_name: "Masjid Agung Bandung",
      maps_url: "https://maps.google.com",
    },
    {
      event_type: "resepsi",
      title: "Resepsi",
      event_date: "2026-08-22",
      event_time: "12:00",
      location_name: "The Trans Luxury Hotel Bandung",
      maps_url: "https://maps.google.com",
    },
  ],
  order_addons: [
    {
      addon_slug: "express",
      addon_name: "Express pengerjaan",
      price_snapshot: 49000,
    },
  ],
  order_assets: [],
  guestbook_entries: [
    {
      guest_name: "Sarah & Budi",
      message: "Selamat menempuh hidup baru. Semoga selalu bahagia.",
      created_at: "2026-05-14T08:30:00+00:00",
    },
    {
      guest_name: "Mia",
      message: "Barakallah, lancar sampai hari H.",
      created_at: "2026-05-14T09:00:00+00:00",
    },
  ],
};
